services:

  monolith:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: monolith
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USERNAME: fl_advisor
      DB_PASSWORD: fl_advisor
    volumes:
      - ./src/main/resources/db/migration/data:/app/data
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8083:8080"   # Web app
      - "5005:5005"   # Debug port
    #volumes:
      # Mount JAR for rebuild-free updates
     # - ./build/libs/flight-atdd-0.0.1-SNAPSHOT.jar:/app/app.jar
      # Optional: Mount source for live reload (if using devtools)
      # - ./src:/app/src
    command: >
      sh -c '
        echo "🧩 Waiting for MySQL...";
        until nc -z mysql 3306; do sleep 2; done;
        echo "🚀 Starting Monolith with debug on port 5005...";
        java -Xmx4g -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -jar /app/app.jar
      '

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: flight_atdd
    command: --local-infile=1 --init-file /docker-entrypoint-initdb.d/database.sql
    ports:
      - "3307:3306"
    volumes:
      - ./volumes/mysql:/var/lib/mysql
      - ./db-init/database.sql:/docker-entrypoint-initdb.d/database.sql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-psecret" ]
      interval: 5s
      retries: 10
      timeout: 5s

